#!/bin/bash

sudo nohup 'sudo python led.py cw' &>/dev/null &
ledPID=`pidof -x led.py`

sudo nohup ./suresine/loop_suresine &>/dev/null &
suresinePID=`pidof -x loop_suresine`

sudo nohup 'sudo python ./currentSensors/readADC.py' &>/dev/null &
ledPID=`pidof -x led.py`